### ISSUE TITLE
SSL error when browsing https://kirakira.keii.dev/

### ISSUE THREAD

**Issue by giovannibonetti** [dinkelspiel/kirakira#15]
Hi! Thanks for starting this promising project, and I hope it will become popular!

Anyway, I just tried to access [the project's website](https://kirakira.keii.dev/) on Chrome for macOS, but got an SSL error:
<img width="557" alt="image" src="https://github.com/user-attachments/assets/a9aec3ee-32f1-4254-96d3-c2902ab70047">

When trying to fetch it with cURL I get a similar error:

```
~ curl -v https://kirakira.keii.dev/
* Host kirakira.keii.dev:443 was resolved.
* IPv6: (none)
* IPv4: 135.181.176.105
*   Trying 135.181.176.105:443...
* Connected to kirakira.keii.dev (135.181.176.105) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
* Closing connection
curl: (35) LibreSSL/3.3.6: error:1404B438:SSL routines:ST_CONNECT:tlsv1 alert internal error
```

**Comment by dinkelspiel** [comment]
This was an issue with deployment and is now resolved
